// This file has been autogenerated from a class added in the UI designer.

using System;
using CharterUser.Common.Extensions;
using Foundation;
using UIKit;

namespace CharterUser
{
	public partial class CreateUserTableViewCell : UITableViewCell
	{
		public UILabel TitleLabel { get; } = new UILabel();
		public UITextField InputField { get; } = new UITextField();
		public UISwitch Switch { get; } = new UISwitch();

		public CreateUserTableViewCell(IntPtr handle) : base (handle)
		{
			CommonInit();
		}
		
		public CreateUserTableViewCell(UITableViewCellStyle style, NSString reuseIdentifier) : base(style, reuseIdentifier)
		{
			CommonInit();
		}

		void CommonInit()
		{
			TitleLabel.TranslatesAutoresizingMaskIntoConstraints = false;
			InputField.TranslatesAutoresizingMaskIntoConstraints = false;
			Switch.TranslatesAutoresizingMaskIntoConstraints = false;

			TitleLabel.Font = UIFont.SystemFontOfSize(17);
			InputField.Font = UIFont.SystemFontOfSize(20);

			ContentView.AddSubview(TitleLabel);
			ContentView.AddSubview(InputField);
			ContentView.AddSubview(Switch);

			TitleLabel.AlignEdgesWithSuperview(RectEdge.Leading | RectEdge.Top, new UIEdgeInsets(16, 16, 16, 16));
			
			InputField.PinVerticalSpacing(TitleLabel, 16);
			InputField.AlignEdgesWithSuperview(RectEdge.Leading | RectEdge.Bottom | RectEdge.Trailing, 
				new UIEdgeInsets(16, 16, 16, 16));

			Switch.PinHorizontalSpacing(TitleLabel, 16);
			Switch.AlignEdgesWithSuperview(RectEdge.Trailing, new UIEdgeInsets(0,0,0,16));
			Switch.AlignVerticalCenter(TitleLabel);
			Switch.Hidden = true;
		}

		public void ToggleSwitchVisibility()
		{
			InputField.Hidden = !InputField.Hidden;
			Switch.Hidden = !Switch.Hidden;
		}
	}
}
